# Generated by Django 2.0.3 on 2018-04-03 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('booking_system', '0002_auto_20180403_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterowner',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='theater',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TheaterOwner',
        ),
    ]
