# Generated by Django 2.0.3 on 2018-04-05 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_auto_20180404_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
