# Generated by Django 2.0.3 on 2018-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0011_auto_20180328_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
