# Generated by Django 2.0.3 on 2018-03-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0012_auto_20180329_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_identifier',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='booking_system.Seat'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='booking_system.StatusType'),
            preserve_default=False,
        ),
    ]
