# Generated by Django 2.0.3 on 2018-04-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0015_auto_20180401_1116'),
    ]

    operations = [
        #migrations.RenameField(
        #    model_name='userprofile',
        #    old_name='date_of_birth',
        #    new_name='dob',
        #),
    ]
