# Generated by Django 2.0.3 on 2018-04-01 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0016_auto_20180401_1119'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='userprofile',
        #    name='dob',
        #    field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        #),
    ]
