# Generated by Django 2.0.3 on 2018-04-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0018_auto_20180401_1123'),
    ]

    operations = [
    #    migrations.RemoveField(
    #        model_name='userprofile',
    #        name='dob',
    #    ),
    ]
