# Generated by Django 2.0.3 on 2018-04-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0019_remove_userprofile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterowner',
            name='age',
        ),
    ]
